services:
  postgres:
    container_name: ${POSTGRES_DOCKER_NAME}
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ADMINISTRATORS_TEAM_NAME: ${ADMINISTRATORS_TEAM_NAME}
      PGPORT: ${PGPORT}
    volumes:
      - ${POSTGRES_DATABASE_DIRECTORY}:/var/lib/postgresql/data
      - ./backend/db_data:/app
    ports:
      - "${PGPORT}:${PGPORT}"
    networks:
      - backend
    restart: on-failure


networks:
  backend:
    driver: bridge