// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]
use crate::schema::users;
use diesel::prelude::*;
use diesel::r2d2::{ConnectionManager, PooledConnection};

#[derive(
    Queryable,
    Debug,
    Eq,
    PartialEq,
    Clone,
    Default,
    Identifiable,
    QueryableByName,
    Insertable,
    Selectable,
    AsChangeset,
)]
#[diesel(table_name = users)]
pub struct User {
    pub id: i32,
    pub first_name: crate::custom_types::NonEmptyTextRust,
    pub middle_name: Option<crate::custom_types::NonEmptyTextRust>,
    pub last_name: crate::custom_types::NonEmptyTextRust,
}

impl User {
    pub fn insert(
        &self,
        connection: &mut PooledConnection<ConnectionManager<diesel::prelude::PgConnection>>,
    ) -> Result<Self, diesel::result::Error> {
        diesel::insert_into(users::table)
            .values(self)
            .get_result(connection)
    }

    pub fn get(
        id: i32,
        connection: &mut PooledConnection<ConnectionManager<diesel::prelude::PgConnection>>,
    ) -> Result<Self, diesel::result::Error> {
        users::table.find(id).first(connection)
    }
}
